insert into student (first_name, second_name, enter_year) values ('Гоша', 'Куценко', 1940);
insert into student (first_name, second_name, enter_year) values ('Григорий', 'Лепс', 1920);
insert into student (first_name, second_name, enter_year) values ('Аркадий', 'Укупник', 1960);
insert into student (first_name, second_name, enter_year) values ('Наталья', 'Королева', 1915);
insert into student (first_name, second_name, enter_year) values ('Сергей', 'Зверев', 1970);
insert into student (first_name, second_name, enter_year) values ('Валентина', 'Заболотная', 1970);
insert into student (first_name, second_name, enter_year) values ('Генадий', 'Карабанов', 1970);

insert into subject (student_id, title) values (1, 'Физика');
insert into subject (student_id, title) values (2, 'Математика');
insert into subject (student_id, title) values (2, 'История');
insert into subject (student_id, title) values (4, 'Физ-ра');
insert into subject (student_id, title) values (5, 'Физика');
insert into subject (student_id, title) values (3, 'Математика');
insert into subject (student_id, title) values (5, 'История');
insert into subject (student_id, title) values (1, 'Физ-ра');
insert into subject (student_id, title) values (3, 'Физика');
insert into subject (student_id, title) values (4, 'Математика');
insert into subject (student_id, title) values (4, 'Математика');

insert into mark (student_id, subject_id, mark) values (1 ,1, 2);
insert into mark (student_id, subject_id, mark) values (2, 2, 3);
insert into mark (student_id, subject_id, mark) values (2, 3, 4);
insert into mark (student_id, subject_id, mark) values (4, 4, 5);
insert into mark (student_id, subject_id, mark) values (5, 5, 4);
insert into mark (student_id, subject_id, mark) values (3, 6, 3);
insert into mark (student_id, subject_id, mark) values (5, 7, 2);
insert into mark (student_id, subject_id, mark) values (1, 8, 4);
insert into mark (student_id, subject_id, mark) values (3, 9, 5);
insert into mark (student_id, subject_id, mark) values (4, 10, 1);
insert into mark (student_id, subject_id, mark) values (1, 1, 1);
insert into mark (student_id, subject_id, mark) values (2, 2, 2);
insert into mark (student_id, subject_id, mark) values (2, 3, 3);
insert into mark (student_id, subject_id, mark) values (4, 4, 5);
insert into mark (student_id, subject_id, mark) values (5, 5, 4);
insert into mark (student_id, subject_id, mark) values (3, 6, 3);
insert into mark (student_id, subject_id, mark) values (5, 7, 2);
insert into mark (student_id, subject_id, mark) values (1, 8, 4);
insert into mark (student_id, subject_id, mark) values (3, 9, 2);
insert into mark (student_id, subject_id, mark) values (4, 10, 1);
insert into mark (student_id, subject_id, mark) values (1, 1, 5);
insert into mark (student_id, subject_id, mark) values (2, 2, 5);
insert into mark (student_id, subject_id, mark) values (2, 3, 4);
insert into mark (student_id, subject_id, mark) values (4, 4, 3);
insert into mark (student_id, subject_id, mark) values (5, 5, 5);
insert into mark (student_id, subject_id, mark) values (3, 6, 2);
insert into mark (student_id, subject_id, mark) values (5, 7, 1);
insert into mark (student_id, subject_id, mark) values (1, 8, 5);
insert into mark (student_id, subject_id, mark) values (3, 9, 3);
insert into mark (student_id, subject_id, mark) values (4, 10, 4);